### ISSUE TITLE
Links of example tests are broken

### ISSUE THREAD

**Issue by TheQuantumPhysicist** [leptos-rs/book#120]
https://book.leptos.dev/testing.html

Some tests have 404 in their links, like [Playwright with counters_stable](https://github.com/leptos-rs/leptos/tree/main/examples/counters_stable/e2e) and [wasm-bindgen-test with counters_stable](https://github.com/leptos-rs/leptos/tree/main/examples/counters_stable/tests/web).

**Comment by gbj** [comment]
Thanks for letting me know! That example was removed when the examples all migrated over to stable, and we inadvertently removed the e2e tests with Playwright as well. I've restored those and updated the links in the book, so all should work now. (Note that some now link to the 0.6 branch, which is what the book is written for, while the Playwright example is to the main branch where I've restored it.)
