### ISSUE TITLE
section 9.3 still not porting to 0.7 version

### ISSUE THREAD

**Issue by dlintw** [leptos-rs/book#138]
section 9.3 still not porting to 0.7 version

**Comment by gbj** [comment]
Could you say a little more? I see that the sandbox example is out of date, and can update that -- is there anything else you noticed that is dated?

**Comment by dlintw** [comment]
section 9.4 also exist out dated example.

[The <A/> Component](https://book.leptos.dev/router/19_a.html#the-a-component)

**Comment by dlintw** [comment]
maybe quick search those examples which use `use leptops::*;` instead of `use leptos::prelude::*;`

**Comment by gbj** [comment]
Should be fixed by [51b6149](https://github.com/leptos-rs/book/commit/51b6149e45eb9d24e11268f933f4f5bf7bd25b99)
