### ISSUE TITLE
section 3.5  Iterating over More Complex Data with  missing example of 'store'

### ISSUE THREAD

**Issue by dlintw** [leptos-rs/book#139]
If possible, could also including a code example. And including a full example for all 4 options?

**Comment by gbj** [comment]
Thanks! Added the TODO section in [9f70015](https://github.com/leptos-rs/book/commit/9f70015804341a6edea7360be6b587453e29ff07)

I do not think providing the full example for all 4 options is actually helpful -- Each example does provide a full snippet for what actually needs to *change*, and I think it's more important for people to read the surrounding text to understand what does and doesn't change than it is to be able to copy and paste the complete examples.
