### ISSUE TITLE
"Global State Management" Chapter - add a "struct of signals" option & example

### ISSUE THREAD

**Issue by diversable** [leptos-rs/book#4]
Add a new option and example to the Global State Management chapter that describes passing state down using a struct of signals.

Recommended by 'gbj' on Discord:
"""
Skimming over it[the Global State Management chapter], I see the recommendations as
**you do not need this chapter**
Option 1 URL should drive global state
Option 2 passing signals through context or props
Option 3 global state struct and slices

Maybe 3 should be 4, and a new Option 3 should be inserted with a struct of signals
"""

**Comment by gbj** [comment]
Closed as of stores section in 0.7 book update.
