### ISSUE TITLE
Add part about `on_cleanup`

### ISSUE THREAD

**Issue by tyoeer** [leptos-rs/book#43]
`on_cleanup` is never mentioned, yet needed when dealing with for example `set_timeout`/`set_interval`. Their callback still gets run after navigating to a different page, even though any resources it accesses no longer exist, leading to an error. This can only be prevented by clearing them in `on_cleanup`.

**Comment by tyoeer** [comment]
Somewhere next to `create_effect` seems the most sensible to me. They're both part of the interaction between the reactive system and the non-reactive world.

**Comment by gbj** [comment]
Done in 20d7685a740093ec0df7a12208f7a6055e14856d
