### ISSUE TITLE
bold text is not rendering correctly

### ISSUE THREAD

**Issue by blorbb** [leptos-rs/book#62]
Just noticed that bold text isn't actually being rendered properly.

![image](https://github.com/leptos-rs/book/assets/88137137/abf65222-21d0-4a4b-8346-e634b5af106e)

Vs source code: https://github.com/leptos-rs/book/blob/main/src/view/05_forms.md?plain=1#L5

The `<strong>` element is present, but it's not styled properly. I think it's probably the font that's being downloaded, there is no `bold` weight loaded so it just looks like normal text.

I'm not super familiar with mdbook, so I'm not sure how to fix this.

**Comment by gbj** [comment]
That's quite weird: here it is for me in light and dark mode. I wonder if this wa an ephemeral issue with the font download for you, or some kind of browser discrepancy?

![Screenshot 2024-02-16 at 1 50 13 PM](https://github.com/leptos-rs/book/assets/286622/dc9d8dd0-ea52-4e3e-bfc0-391b8863b1ee)

![Screenshot 2024-02-16 at 1 50 09 PM](https://github.com/leptos-rs/book/assets/286622/2009827a-1e5a-4184-b760-c768ad594338)

**Comment by blorbb** [comment]
oh my bad I think I had an incorrectly installed font that was screwing it up, it works fine now.
