### ISSUE TITLE
On windows running VSCode, the terminal command trunk serve --open fails because it can't open the browser

### ISSUE THREAD

**Issue by xabra** [leptos-rs/book#93]
`trunk serve --open` fail with this error:
 ERROR error opening browser error=Custom { kind: Other, error: "Launcher \"cmd\" \"/c\" \"start\" \"\" \"http://::1:8080/\" failed with ExitStatus(ExitStatus(1))" }

Workaround is to just run `trunk serve`
then ctrl-click on the link provided in the terminal:  `http://127.0.0.1:8080/`

**Comment by gbj** [comment]
Thanks. I've seen this issue pop up once or twice before and it is a known and apparently hard-to-solve issue with Trunk. (I searched for the issue in their repo, which I've seen before, but couldn't find it immediately.)

I'll add a note to the book.
